wandb_version: 1

model_name:
  desc: null
  value: yoloV8-medium-mvd2
architecture:
  desc: null
  value: yolov8
data:
  desc: null
  value: MVDv2
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 16
img_size:
  desc: null
  value: 640
lr:
  desc: null
  value: 0.01
greyscale:
  desc: null
  value: true
model_size:
  desc: null
  value: m
model_path:
  desc: null
  value: /vol/biomedic3/bglocker/ugproj2324/fv220/dev/shark_locator_tests/runs/detect/yolov8m_mvd2/best.pt
conf_treshold:
  desc: null
  value: 0.2
eval_data:
  desc: null
  value: eval1
iou_association_threshold:
  desc: null
  value: 0.5
tracker:
  desc: null
  value: botsort
pretrained:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706413537.376515
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
